In [1]:
import numpy as np
import pandas as pd

<font color='blue'>
  
* [GİRİŞ](#1)
* [NumPy Array'i Oluşturmak](#2)
    1. [ZEROS-ONES-FULL](#3)
    1. [ARANGE-LINSPACE](#4)
    1. [RANDOM.NORMAL - RANDOM.RANDINT](#5)
* [NumPy ÖZELLİKLERİ](#6)
    1. [ndim (Boyut Sayısı)](#7)
    1. [shape (Boyut Bilgisi)](#8)
    1. [size (Toplam Eleman Sayısı)](#9)
    1. [dtype (Array Veri Tipi)](#10)
    1. [RESHAPE](#11)
    1. [CONCATENATE](#12)
    1. [SPLIT](#13)
    1. [SORT](#14)
* [ELEMANLARA ERİŞMEK](#15)
    1. [INDEX ile Elemanlara Erişmek](#16)
    1. [SLICING ile Elemanlara Erişmek](#17)
* [ALT KÜME İŞLEMLERİ (COPY)](#18)
* [FANCY INDEX](#19)
* [KOŞULLU ELEMAN İŞLEMLERİ](#20)
* [MATEMATİKSEL İŞLEMLER](#21)

<a id="1"></a>

# GİRİŞ

NumPy (Numerical Python) bilimsel hesaplamaları hızlı bir şekilde yapmamızı sağlayan bir matematik kütüphanesidir. Numpy’ın temelini numpy dizileri oluşturur. Numpy dizileri python listelerine benzer fakat hız ve işlevsellik açısından python listelerinden daha kullanışlıdır.

Python listelerde listenin her bir elemanı memory de yer alır.

NumPy arrayler grup halinde memoryde tutulur.

### Python listeleri oluşturarak, iki listenin çarpımını bulalım.

In [2]:
a=[1,2,3,4]
b=[9,8,7,6]

In [3]:
ab=[]
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[9, 16, 21, 24]

### Aynı işlemi listeleri NumPy Array e dönüştürerek yapalım.


In [4]:
a_array=np.array([a])
b_array=np.array([b])

In [5]:
a_array*b_array

array([[ 9, 16, 21, 24]])

##### NumPy Arrayler ile işlem yapmak daha kolay

<a id="2"></a>

# NumPy Array'i Oluşturmak

In [6]:
array1=np.array([10,20,30,40,50])
type(array1)

numpy.ndarray

#### dtype argümanı ile arrayimizi istediğimiz türde oluşturabiliriz.

In [7]:
np.array([2.88,360,8.77,30,20],dtype="int")

array([  2, 360,   8,  30,  20])

<a id="3"></a>

<font color='purple'>
    
    
### ZEROS-ONES-FULL

In [8]:
# ZEROS
np.zeros(10,dtype="float")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#ONES
np.ones(5,dtype="str")

array(['1', '1', '1', '1', '1'], dtype='<U1')

In [10]:
#FULL
np.full((4,4),5)

# 5 sayısından oluşan 4x4 lük matris oluşturduk.

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

<a id="4"></a>

<font color='purple'>
    
    
### ARANGE-LINSPACE

In [11]:
# ARANGE
np.arange(0,100,5)
# 0 dan 100 e kadar (100 dahil değil!) 
#5 erli sayılardan array oluşturduk.

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [12]:
# LINSPACE
np.linspace(0,1,20)
# 0-1 arasında 20 float number üretir.
# array 0 ile başlar 1 ile biter

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<a id="5"></a>

<font color='purple'>
    
    
### RANDOM.NORMAL - RANDOM.RANDINT

In [13]:
# RANDOM.NORMAL
np.random.normal(20,8,(2,2))
# Ortalaması=20
# Standart Sapması=8
# olan 2x2 lik array oluşturduk

array([[25.43503461, 41.07231272],
       [ 5.47256232,  6.80909938]])

In [14]:
# RANDOM.RANDINT
np.random.randint(0,20,(4,4))
# 0-20 arasında ki sayılarla 4x4 lük array olşturduk

array([[11,  1,  7,  6],
       [ 1,  7, 13,  1],
       [19, 10, 11, 18],
       [ 0, 14, 17,  8]])

<a id="6"></a>

# NumPy ÖZELLİKLERİ
*       ndim: Boyut Sayısı
*       shape: Boyut Bilgisi
*       size: Toplam Eleman Sayısı
*       dtype: Array in Veri Tipi

<a id="7"></a>
## ndim (Boyut Sayısı)

In [15]:
h=np.random.randint(0,10,(3,3))
h

array([[1, 1, 6],
       [8, 2, 8],
       [6, 5, 0]])

In [16]:
h.ndim

2

<a id="8"></a>

## shape (Boyut Bilgisi)

<a id="8"></a>



In [17]:
h.shape

(3, 3)

<a id="9"></a>

## size (Toplam Eleman Sayısı)

In [18]:
h.size

9

<a id="10"></a>

## dtype (Array Veri Tipi)

In [19]:
h.dtype

dtype('int64')

<a id="11"></a>

## RESHAPE

In [20]:
k=np.arange(1,10)
k

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
k.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<a id="12"></a>

### CONCATENATE

In [22]:
x=np.array([9,8,7])
y=np.array([6,5,4])

In [23]:
np.concatenate([x,y])

array([9, 8, 7, 6, 5, 4])

### İKİ BOYUTTA CONCATENATE

In [24]:
xx=np.array([[1,2,3],[4,5,6]])
yy=np.array([[3,5,7],[9,5,1]])

In [25]:
# AXIS=1
np.concatenate([xx,yy],axis=1) 
# Sütun olarak birleştirir

array([[1, 2, 3, 3, 5, 7],
       [4, 5, 6, 9, 5, 1]])

In [26]:
# AXIS=0
np.concatenate([xx,yy],axis=0)
# Satır olarak birleştirir

array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 7],
       [9, 5, 1]])

<a id="13"></a>

## SPLIT

In [27]:
t=np.array([78,65,33,2,4,9,58,97])
t

array([78, 65, 33,  2,  4,  9, 58, 97])

In [28]:
np.split(t,4)
# 4 array oluşturur.

[array([78, 65]), array([33,  2]), array([4, 9]), array([58, 97])]

In [29]:
np.split(t,[3,5])
# 3 -> 0-1-2. elemanı bir array olarak ayır.
# 5 -> 5. eleman ve gerisini bir array olarak ayır.
# Kalan elemanları başka bir array olarak ayır.

[array([78, 65, 33]), array([2, 4]), array([ 9, 58, 97])]

In [30]:
# Ayırdığımız arrayleri kullanmak istersek:

j,i,r=np.split(t,[3,5])
j,i,r

(array([78, 65, 33]), array([2, 4]), array([ 9, 58, 97]))

### İKİ BOYUTTA SPLIT

In [31]:
tt=np.arange(16).reshape(4,4)
tt

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
# VERTICAL SPLIT (vsplit)
np.vsplit(tt,[2])
# YATAY
# Oluşturduğumuz 4x4 lük matrisi 2 ye böldük.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [33]:
# HORIZANTAL SPLIT (hsplit)
np.hsplit(tt,[2])
# DİKEY
# Her satırın ilk iki elemanı birinci arraye
# kalanlar ikinci arraye

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

<a id="14"></a>

## SORT

In [34]:
s=np.array([8,5,2,7,4])

##### np.sort(s) s arrayinin orjinal halini bozmaz.
##### Sort edilmiş halini kullanmak istersek yeniden atama yapmamız gerekir.

In [35]:
np.sort(s)

array([2, 4, 5, 7, 8])

##### Python un sort() fonksiyonu s arrayinin orjinalini değiştirir.

In [36]:
s.sort()
s

array([2, 4, 5, 7, 8])

### İKİ BOYUTLU ARRAYLERDE SORT

In [37]:
ss=np.random.randint(0,20,(4,4))
ss

array([[ 0,  1,  5, 15],
       [11,  2, 19,  3],
       [17,  1, 16,  8],
       [15,  1,  6,  4]])

In [38]:
# AXIS=0
np.sort(ss,axis=0)
# Her bir sütunu kendi içinde küçükten büyüğe sıralar.

array([[ 0,  1,  5,  3],
       [11,  1,  6,  4],
       [15,  1, 16,  8],
       [17,  2, 19, 15]])

In [39]:
# AXIS=1
np.sort(ss,axis=1)
# Her bir satırı kendi içinde küçükten büyüğe sıralar.

array([[ 0,  1,  5, 15],
       [ 2,  3, 11, 19],
       [ 1,  8, 16, 17],
       [ 1,  4,  6, 15]])

<a id="15"></a>

# ELEMANLARA ERİŞMEK

<a id="16"></a>

## INDEX ile Elemanlara Erişmek

In [40]:
z=np.random.randint(10,size=10)
z

array([8, 7, 9, 7, 5, 5, 8, 6, 5, 4])

In [41]:
z[-1] # Son eleman.

4

In [42]:
z[0]=97 # İlk elemanı değiştirdik

In [43]:
z

array([97,  7,  9,  7,  5,  5,  8,  6,  5,  4])

### İKİ BOYUTTA İNDEX

In [44]:
zz=np.random.randint(0,20,(3,5))
zz

array([[17, 19,  2,  4, 16],
       [ 0, 14, 17,  0,  2],
       [17,  8, 12, 19,  9]])

In [45]:
zz[1,3] 
# 1 -> Satır
# 3 -> Sütun

0

In [46]:
zz[1,3]=97
zz

array([[17, 19,  2,  4, 16],
       [ 0, 14, 17, 97,  2],
       [17,  8, 12, 19,  9]])

<font color='red'>

### NumPy Array lerde sonradan eklenilen farklı türdeki değişkeni arrayin var olan elemanlarının türüne çevirir. Var olan sistemi bozmaz

In [47]:
zz[1,4]= 2.2 
zz
# Eklenilen float sayıyı Array e Integer olarak ekledi.

array([[17, 19,  2,  4, 16],
       [ 0, 14, 17, 97,  2],
       [17,  8, 12, 19,  9]])

<a id="17"></a>

# SLICING ile Elemanlara Erişmek

In [48]:
w=np.arange(40,50)
w

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [49]:
w[0:3]
w[:3]
# İlk 3 elemanı verir.

array([40, 41, 42])

In [50]:
w[5:]
# 5. elemandan (5. eleman dahil) arrayin sonuna kadar olan elemanları verir.

array([45, 46, 47, 48, 49])

In [51]:
w[0::2]
# 0 -> Başlangıç indexi
# 2 -> 2 şerli

array([40, 42, 44, 46, 48])

In [52]:
w[3::3]
# 3 -> Başlangıç indexi
# 3 -> 3 erli

array([43, 46, 49])

## İKİ BOYUTTA SLICE

### [satır,sütun]

In [53]:
ww=np.arange(1,26).reshape(5,5)
ww

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [54]:
ww[:,0]
#İlk sütun

array([ 1,  6, 11, 16, 21])

In [55]:
ww[0,:]
# İlk satır

array([1, 2, 3, 4, 5])

In [56]:
ww[0:2,0:3]
# İlk 2 satır
# İlk 3 sütun

array([[1, 2, 3],
       [6, 7, 8]])

<a id="18"></a>

# ALT KÜME İŞLEMLERİ (COPY)

##### alt_kume de değiştirdiğimiz eleman p ana kümesinide etkiler.

In [57]:
p=np.random.randint(10,size=(5,5))
p

array([[5, 7, 3, 5, 5],
       [7, 1, 2, 8, 4],
       [7, 1, 5, 8, 3],
       [6, 2, 0, 1, 7],
       [5, 2, 6, 3, 3]])

In [58]:
alt_kume=p[0:3,0:2]
alt_kume

array([[5, 7],
       [7, 1],
       [7, 1]])

In [59]:
alt_kume[0,0]=999
alt_kume

array([[999,   7],
       [  7,   1],
       [  7,   1]])

In [60]:
p

array([[999,   7,   3,   5,   5],
       [  7,   1,   2,   8,   4],
       [  7,   1,   5,   8,   3],
       [  6,   2,   0,   1,   7],
       [  5,   2,   6,   3,   3]])

#### Ana kümeyi bozmamak için copy() metodunu kullanırız.

In [61]:
alt_kume2=p[0:3,0:2].copy()
alt_kume2

array([[999,   7],
       [  7,   1],
       [  7,   1]])

In [62]:
alt_kume2[0,0]=97
alt_kume2

array([[97,  7],
       [ 7,  1],
       [ 7,  1]])

In [63]:
p

array([[999,   7,   3,   5,   5],
       [  7,   1,   2,   8,   4],
       [  7,   1,   5,   8,   3],
       [  6,   2,   0,   1,   7],
       [  5,   2,   6,   3,   3]])

<a id="19"></a>

# FANCY INDEX

In [64]:
u=np.arange(0,30,3)
u

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [65]:
[u[1],u[3],u[3]] # İstediğimiz index deki sayıları aldık

[3, 9, 9]

In [66]:
fancy_list=[1,3,5]
# İstediğimiz elemanların index lerinden oluşan bir liste oluşturduk.
u[fancy_list]
# Arrayimizin içinde listeyi çağırdık.

array([ 3,  9, 15])

## İKİ BOYUTTA FANCY

In [67]:
uu=np.random.randint(10,size=(3,3))
uu

array([[9, 3, 0],
       [5, 2, 6],
       [6, 2, 8]])

In [68]:
satir=np.array([0,1])
sutun=np.array([1,2])
uu[satir,sutun]

array([3, 6])

<a id="20"></a>

# KOŞULLU ELEMAN İŞLEMLERİ

In [69]:
r=np.array([1,2,3,4,5])

In [70]:
r>3
# 3 den büyük değerler için TRUE
# 3 den küçük değerler için FALSE

array([False, False, False,  True,  True])

In [71]:
r[r>3]
# 3 den büyük değerleri gösterir

array([4, 5])

In [72]:
r[r!=3]
# 3 dışındaki değerleri verir

array([1, 2, 4, 5])

<a id="21"></a>

# MATEMATİKSEL İŞLEMLER

In [73]:
r-1

array([0, 1, 2, 3, 4])

In [74]:
r**2

array([ 1,  4,  9, 16, 25])

In [75]:
np.subtract(r,1) 
#-1

array([0, 1, 2, 3, 4])

In [76]:
np.add(r,5)
# +5

array([ 6,  7,  8,  9, 10])

In [77]:
np.multiply(r,3)
# x3

array([ 3,  6,  9, 12, 15])

In [78]:
np.divide(r,2)
# /2

array([0.5, 1. , 1.5, 2. , 2.5])

In [79]:
np.power(r,4)
# 4. kuvvetini al

array([  1,  16,  81, 256, 625])

In [80]:
np.absolute(np.array([-9,6,-10,-5]))
# mutlak değer

array([ 9,  6, 10,  5])

In [81]:
np.cos(180)
# Trigonometrik ifadeler.

-0.5984600690578581

In [82]:
np.log(np.array([10,100,200]))

array([2.30258509, 4.60517019, 5.29831737])

In [83]:
np.log2(np.array([4,16,64]))
# 2 tabanın da logaritma

array([2., 4., 6.])

## NumPy ile İki Bilinmeyenli Denklem Çözümü

5*x0+x1=12

x0+3*x1=10

In [84]:
d=np.array([[5,1],[1,3]])
f=np.array([12,10])

In [85]:
sonuc=np.linalg.solve(d,f)
sonuc

array([1.85714286, 2.71428571])